version: '3' 

services: 
  nginx-proxy:
    image: nginx:1.17.8
    container_name: nginx-proxy
    hostname: nginx-proxy
    volumes:
      - ./conf.d/nginx:/etc/nginx/conf.d
      - certbot:/etc/letsencrypt
      - webroot:/var/www/certbot_webroot
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - APP_URL=${APP_URL}
      - CERTBOT_CERT_NAME=${CERTBOT_CERT_NAME}
    command: >
      /bin/bash -c "
          envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf \
          && exec nginx -g 'daemon off;'
      "
    networks:
      mynet:
        ipv4_address: 172.28.0.2

  app:
    build:
      context: ./

    container_name: app

    restart: "on-failure"

    expose:
      - 80
      - 5000
    ports: 
      - 80:80
      - 5000:5000

    volumes:
      - './:/app'
      - '/app/node_modules'

    environment: 
      PORT: 80
      CHOKIDAR_USEPOLLING: "true"
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"

    networks: 
      mynet:
        ipv4_address: 172.28.0.5

networks:
  mynet:
    name: mynet
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/24"

volumes:
  certbot:
    name: certbot
  webroot:
    name: webroot